version: '3'

services:

  db:

    image: postgres:12.4

    volumes:
      - postgres_data:/var/lib/postgresql/data/

    env_file:
      - ./.env.example
  web:
    build: .
    image: sgoldort/yamdb_final:latest
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    depends_on:
      - db
    env_file:
      - ./.env.example
  nginx:
    image: nginx:1.19.6
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
