version: '3'

services:

  db:
    image: postgres:12.4
    environment:
      - POSTGRES_DB=yamdb
      - POSTGRES_USER=yatube_user
      - POSTGRES_PASSWORD=yatube_password
      - DB_HOST=db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    env_file:
      - ./.env.example

  web:
    image: sgoldort/yamdb_final:latest
    restart: always
    command: gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    depends_on:
      - db
    links:
      - db:db
    env_file:
      - ./.env.example

  nginx:
    image: nginx:1.19.6
    volumes:
      - ./nginx/default.conf:/etc/nginx.conf/conf.d/default.conf
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
