version: '3.8'

services:

  db:

    image: postgres:12.4

    volumes:
      - postgres_data:/var/lib/postgresql/data/

    env_file:
      - ./.env
  web:
    build: .
    restart: always
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    ports:
      - "8000:8000"

    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.6
      restart: always
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - static_volume:/code/staticfiles
        - media_volume:/code/media
      ports:
        - "80:80"
      depends_on:
        - web

volumes:
  postgres_data:
  static_volume:
  media_volume: